version: "3.4"
x-base: &base
  image: contour-dev
  build:
    context: ./devops
  env_file: .docker-development-vars
  environment:
    - BUNDLE_PATH=/app/vendor/bundle
  volumes:
    - .:/app:cached
    - ./vendor/bundle:/app/vendor/bundle:delegated
    - ./node_modules:/app/node_modules:delegated
services:
  app:
    <<: *base
    command: bundle exec puma -C config/puma.rb
    ports:
      - 3000:3000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:11-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust 
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  jsbuild:
    <<: *base
    command: yarn build --watch
    ports:
      - '3035:3035'
volumes:
  postgres_data:
